### ISSUE TITLE
Edge retrieve TypeMismatchError

### ISSUE THREAD

**Issue by federico-galfione** [aurelia/fetch-client#81] opened 2016-10-27 09:31 UTC
**I'm submitting a bug report**
- **Operating System:**
  Windows 10
- **Browser:**
  Edge 
- **Language:**
  TypeScript

I'm having trouble with Edge and I can't retrieve data from API. 
Every time I get a `TypeMismatchError` with no other details about the error.
I breakpointed the API, but the requests don't reach it.
Everything works great on other browsers (tested on IE11, Firefox and Chrome).

**Stackoverflow**
http://stackoverflow.com/questions/39960440/typemismatcherror-on-post

**Comment by EisenbergEffect** [comment] 2016-11-02 15:11
We will need more information to help you with this.

**Comment by EisenbergEffect** [comment] 2016-11-19 17:23
Closing due to no follow up from OP after more than two weeks.

**Closed by EisenbergEffect** 2016-11-19 17:23 UTC
Labels: question

**Comment by vegarringdal** [comment] 2016-12-08 19:54
I  also got this problem today, worked fine in every browser except for edge (YAY I love MS browsers)

From what I can tell its edge that have a bug.
Since I can get it to work with a fetch polyfill.

For for anyone else getting this issue, this is how I manged to get it working.

**index.html**
remove the window.fetch
```delete window.fetch```
(you should check if edge)

**main.js/ts**
```import 'whatwg-fetch';```

Why this is happening I dont know, Im getting the issue on a rest api on a database called wakanda Im making a datasource for my [new grid](https://www.gitbook.com/book/vegarringdal/dev-rebuild/details)
, using cors

**Operating System:**
Windows 10
**Browser:**
Edge (Microsoft Edge 38.14393.0.0, Microsoft EdgeHTML 14.14393)
**Language:**
TypeScript

**Comment by vegarringdal** [comment] 2016-12-08 20:09
**Update:**

In edge the body needs to be ```undefined``` when using get, my issue what that I was setting it to null on get requests, that made it fail

Hope this helps others that get this problem

**Comment by fexdev** [comment] 2017-02-22 09:30
Thanks @vegarringdal, I had the same Issue today

**Comment by yannhervy** [comment] 2017-06-15 10:07
I received the same error and it was caused by me accidentally setting one of the headers to null.

**Comment by slovely** [comment] 2017-12-08 11:51
Sorry, I know this is a closed issue, but isn't it still broken in Edge?  In `http-client.js` line [167 ](https://github.com/aurelia/fetch-client/blob/master/src/http-client.js#L167) is the following code:
`let bodyObj = body ? { body } : null;`
so there is no way to set body to `undefined` is there?

**Comment by martynchamberlin** [comment] 2018-06-27 17:55
Gross. Looks like this is still an issue. Here's the SHA link to the thing that @slovely was linking to above: https://github.com/aurelia/fetch-client/blob/d2314104d4451b61f7746039f20d27f74cace632/src/http-client.js#L161

**Comment by EisenbergEffect** [comment] 2018-06-28 00:35
PRs welcome if this is causing you a problem.

**Comment by doktordirk** [comment] 2018-06-30 19:49
@martynchamberlin i had a try with edge and first it complained but still worked and now i dont get the complaint back. anyways, fetch-client is actually not working for you in edge?

**Comment by martynchamberlin** [comment] 2018-06-30 19:54
The problem is that at work we're on a corporate image of Windows 10 that hasn't gotten the spring 2017 updates for Edge. I suspect on a newer version of Edge it would be just fine.

Will do some more exploring and update here accordingly if I find anything.
