### ISSUE TITLE
custom set content-type value not work

### ISSUE THREAD

**Issue by tomsean** [aurelia/fetch-client#43] opened 2016-03-22 07:13 UTC
request.headers.set('Content-Type', body.type);
not work

**Comment by EisenbergEffect** [comment] 2016-03-22 10:15
Please provide us with some more information.
@bryanrsmith This would seem a major bug if true. Could there be something else happening here?

**Comment by tomsean** [comment] 2016-03-23 01:10
yes,when i use aurelia-fetch-client to post json data to server and then i can  find miss "content-type" at  http header,and then debug soure code find can not set content-type success.

**Comment by bryanrsmith** [comment] 2016-03-23 03:29
@tomsean Can you please provide a complete code sample that reproduces the issue?

**Comment by bryanrsmith** [comment] 2016-04-03 18:13
I'm going to go ahead and close this because I can't reproduce and no code sample has been provided. I will definitely investigate if someone can provide a repro.

**Closed by bryanrsmith** 2016-04-03 18:13 UTC

**Comment by Tseberechts** [comment] 2016-05-13 13:34
I have the same problem. I'll try to elaborate.

Using the fetch-client with `.useStandardConfiguration()`

```javascript
this.http.fetch(url, {
      method: 'POST',
      body: json({email: this.email, password: this.password})
    }).then( r => r.json())
      .then(data => {
        console.log(data);
      })
      .catch(e => console.error(e));
```

so, pretty standard.

Now, there should be a `Content-Type: 'application/json'` in the header, thanks to the json helper and the `buildRequest()` function in the aurelia-fetch-client.

...But there isn't. Here is the request:

```
OPTIONS /auth/login HTTP/1.1
Host: *****************
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: POST
Origin: *****************
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
DNT: 1
Referer: *****************
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4,fr;q=0.2,af;q=0.2
```
On further investigation, i viewed every step in the `buildRequest()` function.

Here's the function.

```javascript
function buildRequest(input, init) {
  var defaults = this.defaults || {};
  var request = void 0;
  var body = void 0;
  var requestContentType = void 0;

  var parsedDefaultHeaders = parseHeaderValues(defaults.headers);
  if (Request.prototype.isPrototypeOf(input)) { // = false
    request = input;
    requestContentType = new Headers(request.headers).get('Content-Type');
  } else {
    init || (init = {});
    body = init.body; // body = Blob {size: 34, type: "application/json"}
    var bodyObj = body ? { body: body } : null;
    var requestInit = Object.assign({}, defaults, { headers: {} }, init, bodyObj);
    requestContentType = new Headers(requestInit.headers).get('Content-Type'); // requestContentType = "application/json"
    request = new Request(getRequestUrl(this.baseUrl, input), requestInit); // request.headers is empty
  }
  if (!requestContentType && new Headers(parsedDefaultHeaders).has('content-type')) { // = false
    request.headers.set('Content-Type', new Headers(parsedDefaultHeaders).get('content-type'));
  }
  setDefaultHeaders(request.headers, parsedDefaultHeaders); // request.headers  is empty
  if (body && Blob.prototype.isPrototypeOf(body) && body.type) { // = true
    request.headers.set('Content-Type', body.type); // request.headers is empty
  }
  return request; //request.headers is empty
}
```
Here's the request object which is returned:

```javascript
request: Request
bodyUsed:false
credentials:"same-origin"
headers:Headers
    __proto__:Headers
integrity:""
method:"POST"
mode:"cors"
redirect:"follow"
referrer:"about:client"
url:"***************"
__proto__:Request
```

I hope this could help you saving the problem.
